apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  POSTGRES_DB: "${{ secrets.POSTGRES_DB }}"
  POSTGRES_USER: "${{ secrets.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD }}"
  USER_TOKEN_SECRET: "${{ secrets.USER_TOKEN_SECRET }}"
