name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          cache: 'npm'
      - run: npm
      - run: npm run test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(ECHO $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t diname7/tech-challenge-api:${{ steps.generate_tag.outputs.sha }}.

      - name: Push image
        run: docker push diname7/tech-challenge-api:${{ steps.generate_tag.outputs.sha }}.
