name: Continuos Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen
          # cache: 'npm'
      - run: |
          npm install
          npm run build
      # - run: npm run test
      - name: Generate tag
        id: generate_sha
        run: |
          SHA=$(ECHO $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      # - name: Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build and push Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: |
      #       diname/tech-challenge-fiap-api:latest
      #       diname/tech-challenge-fiap-api:${{ steps.generate_tag.outputs.sha }}

      - name: Build docker image
        run: docker build . -t diname/tech-challenge-fiap-api:${{ steps.generate_sha.outputs.sha }}

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push diname/tech-challenge-fiap-api:${{ steps.generate_sha.outputs.sha }}
          docker tag diname/tech-challenge-fiap-api:${{ steps.generate_sha.outputs.sha }} diname/tech-challenge-fiap-api:latest
          docker push diname/tech-challenge-fiap-api:latest
